[package]
name = "glue-generator"
version = "0.1.0"
authors = ["Tjeu Kayim <15987676+TjeuKayim@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
clang = { version = "1.0.3", features = ["clang_10_0"] }
