on: [pull_request, push]

name: CI

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
    env:
      ZOOM_SDK_DIR: 'C:\ZoomSdk'
    steps:
      - name: Download Zoom SDK
        env:
          ZOOM_SDK_DOWNLOAD: ${{ secrets.ZOOM_SDK_DOWNLOAD }}
        run: |
          $tmpZip = ".\sdk.zip"
          Invoke-WebRequest -Uri $env:ZOOM_SDK_DOWNLOAD -OutFile $tmpZip
          $tmpZip | Expand-Archive -DestinationPath .\
          rm $tmpZip
          mv .\zoom-sdk-windows-5.5.12511.0422 $env:ZOOM_SDK_DIR
          ls $env:ZOOM_SDK_DIR
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1
