on: [pull_request, push]

name: CI

jobs:
  build_and_test:
    name: Build and test
    runs-on: windows-latest
    env:
      ZOOM_SDK_DIR: 'C:\ZoomSdk'
    steps:
      - name: Download Zoom SDK
        env:
          zoom_marketplace_auth_id: ${{ secrets.ZOOM_MARKETPLACE_AUTH_ID }}
          zoom_marketplace_app_id: ${{ secrets.ZOOM_MARKETPLACE_APP_ID }}
        run: |
          $tmpZip = ".\sdk.zip"
          $headers = @{'X-Auth-Token' = $env:zoom_marketplace_auth_id}
          $appId = $env:zoom_marketplace_app_id
          $version = 'v5.5.12511.0422'
          $downloadSdkResponse = Invoke-WebRequest -Uri "https://marketplace.zoom.us/api/v1/apps/${appId}/downloadSdk?title=Windows&type=3&version=${version}" -H $headers
          $downloadSdkResponse = $downloadSdkResponse.Content | ConvertFrom-Json
          Invoke-WebRequest -Uri $downloadSdkResponse.downloadLink -OutFile $tmpZip
          $tmpZip | Expand-Archive -DestinationPath .\
          rm $tmpZip
          mv .\zoom-sdk-windows-5.5.12511.0422 $env:ZOOM_SDK_DIR
          ls $env:ZOOM_SDK_DIR
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1
